<?php

const routes = [
    "/"               => ['HomeController',   'index'],
    "/home"           => ['HomeController',   'index'],
    "/classes/load"   => ['ClassController',  'load'],
    "/classes/show"  => ['ClassController',  'getClass'],
    "/classes/add"    => ['ClassController',  'addClass'],
    "/classes/edit"   => ['ClassController',  'editClass'],
    "/classes/delete" => ['ClassController',  'deleteClass'],
    "/grades/load"    => ['GradeController',  'load'],
    "/grades/show"   => ['GradeController',  'getGrade'],
    "/grades/add"     => ['GradeController',  'addGrade'],
    "/grades/edit"    => ['GradeController',  'editGrade'],
    "/grades/delete"  => ['GradeController',  'deleteGrade'],
    "/scores/load"    => ['ScoreController',  'load'],
    "/scores/show"   => ['GradeController',  'getScore'],
    "/scores/add"     => ['ScoreController',  'addScore'],
    "/scores/edit"    => ['ScoreController',  'editscore'],
    "/scores/delete"  => ['ScoreController',  'deleteScore'],
    "/students/load"    => ['StudentController',  'load'],
    "/students/show"   => ['StudentController',  'getStudent'],
    "/studentss/add"     => ['StudentController',  'addStudent'],
    "/students/edit"    => ['StudentController',  'editStudent'],
    "/students/delete"  => ['StudentController',  'deleteStudent'],
    "/subjects/load"    => ['SubjectController',  'load'],
    "/subjects/show"   => ['SubjectController',  'getSubject'],
    "/subjects/add"     => ['SubjectController',  'addSubject'],
    "/subjects/edit"    => ['SubjectController',  'editSubject'],
    "/subjects/delete"  => ['SubjectController',  'deleteSubject'],
    "/users/load"    => ['UserController',  'load'],
    "/users/show"   => ['UserController',  'getUser'],
    "/users/add"     => ['UserController',  'addUser'],
    "/users/edit"    => ['UserController',  'editUser'],
    "/users/delete"  => ['UserController',  'deleteUser'],
    "/home/load"    => ['HomeController',  'load']
];